name: GriefBoard
version: 1.0
main: ru.griefboard.GriefBoard
api-version: 1.16
description: Sidebar scoreboard in GhostGrief style
softdepend: [LuckPerms]

commands:
  griefboard:
    description: Управление скорбордом
    aliases: [gsb]
    permission: griefboard.admin
  rtp:
    description: Случайная телепортация в основной мир
    permission: griefboard.rtp

permissions:
  griefboard.rtp:
    default: true
  griefboard.admin:
    default: op
